// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sakeurhfemssebptfycs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNha2V1cmhmZW1zc2VicHRmeWNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMjg0MzgsImV4cCI6MjA1OTkwNDQzOH0.EPQihkfsIv0shGV6hz_lSA35ZA9LihG8aPo7Trci3Ec";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);